module.exports = {
  USER_ROLES: {
    ADMIN: 'admin',
    SUB_ADMIN: 'sub_admin',
    MERCHANT: 'merchant',
    SUB_MERCHANT: 'sub_merchant',
    CUSTOMER: 'customer',
    SUB_CUSTOMER: 'sub_customer',
  },
  FILE_MODULES: {
    DEFAULT: 'DEFAULT',
    PROFILE_PICTURE: 'PROFILE_PICTURE',
    PROFILE_COVER: 'PROFILE_COVER',
    COMPANY_LICENSE: 'COMPANY_LICENSE',
    VAT_CERTIFICATE: 'VAT_CERTIFICATE',
    PASSPORT: 'PASSPORT',
    EMIRATES_ID: 'EMIRATES_ID',
    USER_AGREEMENT: 'USER_AGREEMENT',
    WALLET_RECEIPT: 'WALLET_RECEIPT',
    BANK_LOGOS: 'BANK_LOGOS',
    CONTACT_US: 'CONTACT_US',
  },
  DOCUMENT_SIDES: {
    NONE: 'NONE',
    FRONT: 'FRONT',
    BACK: 'BACK'
  },
  NOTIFICATION_TYPES: {
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
    DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
    CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
    MERCHANT_REGISTERED: 'MERCHANT_REGISTERED',
    MERCHANT_REGISTRATION_REQUEST: 'MERCHANT_REGISTRATION_REQUEST',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    PRIMARY_CURRENCY_CHANGED: 'PRIMARY_CURRENCY_CHANGED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    ACCOUNT_SUSPENSION_REVOKED: 'ACCOUNT_SUSPENSION_REVOKED',
    WALLET_DEPOSIT_REQUEST: 'WALLET_DEPOSIT_REQUEST',
    WALLET_DEPOSIT_REQUEST_APPROVED: 'WALLET_DEPOSIT_REQUEST_APPROVED',
    WALLET_DEPOSIT_REQUEST_REJECTED: 'WALLET_DEPOSIT_REQUEST_REJECTED',
    WALLET_DEPOSIT_REQUEST_DELETED: 'WALLET_DEPOSIT_REQUEST_DELETED',
    WALLET_CREDIT_REQUEST: 'WALLET_CREDIT_REQUEST',
    WALLET_CREDIT_REQUEST_APPROVED: 'WALLET_CREDIT_REQUEST_APPROVED',
    WALLET_CREDIT_REQUEST_REJECTED: 'WALLET_CREDIT_REQUEST_REJECTED',
    WALLET_CREDIT_REQUEST_DELETED: 'WALLET_CREDIT_REQUEST_DELETED',
    CREDIT_REQUEST_PAYMENT_REMINDER: 'CREDIT_REQUEST_PAYMENT_REMINDER',
    BOOKING_PURCHASE_ORDER: 'BOOKING_PURCHASE_ORDER',
    BOOKING_SUCCESS: 'BOOKING_SUCCESS',
    BOOKING_FAILED: 'BOOKING_FAILED',
    DOCUMENT_EXPIRED: 'DOCUMENT_EXPIRED',
  },
  OTP_MOTIVE: {
    MISCELLANEOUS: 'MISCELLANEOUS',
    LOGIN: 'LOGIN',
  },
  TRANSACTIONS: {
    MOTIVE: {
      CASH_DEPOSIT: 'CASH_DEPOSIT',
      CHEQUE_DEPOSIT: 'CHEQUE_DEPOSIT',
      BANK_TRANSFER: 'BANK_TRANSFER',
      CARD_DEPOSIT: 'CARD_DEPOSIT',
      CARD_DEPOSIT_REFUNDED: 'CARD_DEPOSIT_REFUNDED',
      CREDIT_REQUEST: 'CREDIT_REQUEST',
      BOOKING: 'BOOKING',
      BOOKING_CANCELLED: 'BOOKING_CANCELLED',
      BOOKING_UPDATED: 'BOOKING_UPDATED',
      CREDIT_PAYMENT: 'CREDIT_PAYMENT',
      CREDIT_CLOSED: 'CREDIT_CLOSED',
    },
    TYPES: {
      CREDIT: 'CREDIT',
      DEBIT: 'DEBIT',
    },
    EXPORT_STATEMENT_TYPES: {
      PDF: 'PDF',
      EXCEL: 'EXCEL',
    }
  },
  PENALTY_PERIOD: {
    DEFAULT: null,
    DAILY: 'DAILY',
    WEEKLY: 'WEEKLY',
    FORT_NIGHT: 'FORT_NIGHT',
  },
  WALLET_DEPOSIT_LOGS: {
    ACTIONS: {
      VISITED: 'VISITED',
      ACCEPTED: 'ACCEPTED',
      SEND_BACK: 'SEND_BACK',
      DELETED: 'DELETED',
    },
    PAGE: {
      LISTING: 'LISTING',
      DETAILS: 'DETAILS',
    }
  },
  PAYBY_ENVIRONMENTS: {
    STAGING: 'STAGING',
    PRODUCTION: 'PRODUCTION',
  },
  PAYBY_MOTIVE: {
    CARD_DEPOSIT: 'CARD_DEPOSIT',
    CREDIT_PAYMENT: 'CREDIT_PAYMENT',
  },
  SERVICE_CHARGE_TYPES: {
    PERCENTAGE: 'percentage',
    AMOUNT: 'amount',
  },
  BOOKING_PRODUCTS: {
    FLIGHT: 'flight',
    HOTEL: 'hotel',
    VISA: 'visa'
  },
  BOOKING_FLIGHT_OPTIONS: {
    ONE_WAY: 'one_way',
    ROUND_TRIP: 'round_trip',
    MULTI_CITY: 'multi_city'
  },
  PASSENGER_TYPES: {
    ADULT: 'Adult',
    CHILD: 'Child',
    INFANT: 'Infant'
  },
  INVESTMENT: {
    MOTIVE: {
      ADD_FUND: 'ADD_FUND',
      RETURN_FUND: 'RETURN_FUND',
      CREDIT_GIVEN: 'CREDIT_GIVEN',
      CREDIT_RETURNED: 'CREDIT_RETURNED',
      PROFIT_RETURNED: 'PROFIT_RETURNED'
    },
    TRANSACTION_TYPES: {
      CREDIT: 'CREDIT',
      DEBIT: 'DEBIT'
    }
  },
  RESOURCES_PLATFORM: {
    ADMIN: 'admin',
    CUSTOMER: 'customer',
    MERCHANT: 'merchant'
  },
  NEWS_BULLETINS: {
    TYPES: {
      ALL_USER: 'all_user',
      ALL_CUSTOMER: 'all_customer',
      ALL_MERCHANT: 'all_merchant',
      CUSTOMER: 'customer',
      MERCHANT: 'merchant'
    }
  }
};
